### ISSUE TITLE
get and set methods

### ISSUE THREAD

**Issue by m1** [bocharsky-bw/Arrayzy#27]
@bocharsky-bw Have you thought about having `get` and `set` methods? e.g.

```
$a = ImmutableArray::create(['key_1' => 'a', 'key_2' =>  'b']);
$a->get('key_1'); // a

$a->set('key_2', 'c');
$a->get('key_2'); // c
```

Also as for multidimensional arrays, you could possible be able to chain `get` e.g.

```
$a = ImmutableArray::create(['key_1' => ['key_2' => 'a']]);
$a->get('key_1')->get('key_2'); // a
```

**Comment by bocharsky-bw** [comment]
I don't like `set`/`get` methods :-1:. We already have setters/getters, check [ArrayAccess](http://php.net/manual/en/class.arrayaccess.php) native PHP interface which Arrayzy already implemented. It's a `offsetSet`, `offsetGet`, `offsetUnset`, and `offsetExists`. So I think it's a bit overhead to have get/set aliases you suggested.

BTW, chaining allowed only if nested array also is an Arrayzy instance, i.e.:

``` php
$a = ImmutableArray::create(['key_1' => ImmutableArray::create(['key_2' => 'a'])]);
$a->get('key_1')->get('key_2'); // a
```

Otherwise it doesn't work. You could check Symfony's [PropertyAccess](http://symfony.com/doc/current/components/property_access/introduction.html) component to do it simpler.

The only useful method, that I see here is adder, wich will simply add new value to the end of array:

```
$a = ImmutableArray::create(['a', 'b']);
$a->add('c');
```

Because `array_push()` is a bit overhead for this task now. So implementation of this method should be:

``` php
public function add($element) {
    $this->elements[] = $element;

     return $this;
}
```

You could add this _adder_ implementation if you want.

**Comment by bocharsky-bw** [comment]
Adder already implemented in https://github.com/bocharsky-bw/Arrayzy/commit/ad56775558e29ed0e956f110565b82e6bc6c8e02
